name: CI
on:
  - push
  - pull_request

jobs:
  build:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    name: 'Test on Node ${{ matrix.node }} and ${{ matrix.os }}'
    runs-on: '${{ matrix.os }}'
    strategy:
      # max-parallel: 1
      matrix:
        node:
          - 18
        os:
          - ubuntu-latest
          # - windows-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3
      - name: 'Setup pnpm'
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: 'Test'
        run: |
          pnpm run regen
          pnpm run test
          pnpm run build
      - name: 'Compatibilty Check'
        run: |
          pnpm run compatibilty_check
